language: ruby
rvm:
  - 2.5
services:
 - postgresql
before_script:
 - bundle exec rails db:create
 - bundle exec rails db:migrate

deploy:
  provider: heroku
  app: hidden-cliffs-27554
  on:
    repo: ajbacon/acebook-true-GrIT
  run:
  - bundle exec rails db:migrate
  api_key:
    secure: "KL9qtYE5IAhNBdG354JuLfGFW+CAekNBBx3VcZtUx+FWx/VeT8KsuagP84fCFsSH/RT5suhJLNNvOkT8ahiLO6TdhgumyiNLegJ+uWzsDsFVu4fD7
T0J60RvuqSGqaSFw7v2puZ6U6o8TJBbw57vTVglRWm5bC0PMi5qJWf9uvTPcF2eN1wPIRSz5IjSD2c0Q0JPyAb9+aGRl8P8QAh8XFkFgwnwru/6fPqa4CEqWm7X2
8TGp4l50CuPxsmozKCxH9U6m9u97FC6xZKOiyOpuXsQkzPPGhfvIyywZE3P7FbNJcnxJCf4rRMFgTwSQ1q1RmERdsxf/IJbsCqh5WevpJ3/8zn/pDiy6hAO0JMQ7
uaNGjQyeO8E5gucJg5HtKtfY7hewY44Te2nOzjp4JfgB9a3m07ZZuq2EwHLLQZcvbgNAKhxbDRw27Hn/Y57qh7VJcmKhUM8xb8Gop8Pozu1IZtxh/bWIfv9jMOHP
IhBayGu20qVEEli4RzyyWviVs/WSNZ1ZvqNb918sw6bEEs80nC8Nvl5TDHjv/H6qB5Chg++yR5hDfCJ1E15IUrM/sgmyOp3N9DTiY3NfE+BD+3h/DF0MtR1naKDg
S8MdbGbuX7Qbc3iFiNwazjmzKvPV7YOoLDTR5F4oKvCl/ttsni+oww1bI+tw+6szOWabvCQ/tw="
