language: ruby
rvm:
- 2.5
services:
- postgresql
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
deploy:
  provider: heroku
  app: hidden-cliffs-27554
  on:
    repo: ajbacon/acebook-true-GrIT
  run:
  - bundle exec rails db:migrate
  api_key:
    secure: ZaTyfipvq0Lb66QfAC5vpegtz8peAUooIFadHd05T9j2l2QqqFDGiIc30ZkpT0yX8NZsfhPtAPmDtc+NYA8NO0HoopZ+5f3TfiqOdW4oQaxeKCJOQdGAXtzCK8IdVeEu7r3iDaJGj5uNysCIIpK7hGZKjh6BbyG+XVuFhG0ST9eUlIu3aWpPJsGZhVgqjUzLX8elvpv6/H8icXtwMgDbI7+VLxn32gZHHQ5nsQVoRozXv15/bo/kexkuYpenFWrzev78CRrLOgN/byOtwFTccdqqk/CvpGgviSQ/+XgVvmHlCNMkUikndKOmCeLesgEAgg2XEROInVKey3NlDed7Fu1IiNP6QJO9OIg3xp4Bk+UCYmQKi3PYw6zGENcyWyrc06QpYKs3nLWI9OhqyluQxQhwDY21YmNo2Olb8GCxZ7H61iSyEHGhAJUeYw+F2WnAm1CrOgttaDPz12Y99P4iDGcsOdRVudqT264dlqqGmi8intEsC5gsSKQrasJguPvIEsSdjxgkeniYZehBFGaHIvYq5pnjCgy4gFFLvMJImNEZgRFVJ4yJL02f/WWi/z+E3iaAuFQa8GBCHSQc1Jk6bUcCkRnCHxAYWKG/lyO7g5+CrYxDwFXLEWNY8tJfu7lWAhf8IWnNjm8AkS2MesbSSFugGWRqg6f3/V8k1FhNhbI=
